### ISSUE TITLE
How to set socket options?

### ISSUE THREAD

**Issue by WestXu** [mental32/zedmq#1]
like this from rust-zmq: https://docs.rs/zmq/0.9.2/zmq/struct.Socket.html#method.set_rcvtimeo

**Comment by mental32** [comment]
Oh hello there. unfortunately this library isn't close to being mature or complete. This functionality simply doesn't exist :( I'd stick with the zmq crate for now if I were you.

**Comment by WestXu** [comment]
Alright. 

The zmq crate depends on libzmq which is painful for some build context. 

Thanks anyway. Feel free to close this one.
